name: AX3600 NSS Build firmware

on: workflow_dispatch

jobs:
    build:
        name: AX3600 NSS Build firmware
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt install -y build-essential \
                  clang \
                  flex \
                  bison \
                  g++ \
                  gawk \
                  gcc-multilib \
                  g++-multilib \
                  gettext \
                  git \
                  libncurses5-dev \
                  libssl-dev \
                  python3-setuptools \
                  rsync \
                  swig \
                  unzip \
                  zlib1g-dev \
                  file \
                  wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4
           
            - name: Update scripts
              run:  ./scripts/feeds update

            - name: Install scripts
              run:  ./scripts/feeds install -a

            - name: Generate config
              run:  cp nss-setup/config-nss.seed .config

            - name: Modify config
              run: sed -i 's/# CONFIG_TARGET_qualcommax_ipq807x_DEVICE_xiaomi_ax3600 is not set/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_xiaomi_ax3600=y/g' .config
                           
            - name: Print initial config we are using
              run: cat .config

            - name: Generate full config
              run:  make defconfig V=s

            - name: Pre-download
              run: make download -j$(nproc) V=s

            - name: Build firmware images
              run: make -j$(($(nproc)+1)) V=s

            - name: Pack packages
              run:  tar cvfz bin/ipq807x.tar.gz -C bin/targets/qualcommax/ipq807x .

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: copy file to server
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                source: bin/ipq807x.tar.gz
                target: uploads/${{ env.SHA }}
