name: AX3600 NSS Build firmware

on: workflow_dispatch

jobs:
    build:
        name: AX3600 NSS Build firmware
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt install -y build-essential \
                  clang \
                  flex \
                  bison \
                  g++ \
                  gawk \
                  gcc-multilib \
                  g++-multilib \
                  gettext \
                  git \
                  libncurses5-dev \
                  libssl-dev \
                  python3-setuptools \
                  rsync \
                  swig \
                  unzip \
                  zlib1g-dev \
                  file \
                  wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4
           
            - name: Update feeds
              run:  ./scripts/feeds update

            - name: Install feeds
              run:  ./scripts/feeds install -a

            - name: Generate config
              run:  cp nss-setup/config-nss.seed .config

            - name: Generate AX3600 NSS Config
              run: cp nss-setup/config-nss.seed .config 
               && sed -i 's/# CONFIG_TARGET_qualcommax_ipq807x_DEVICE_xiaomi_ax3600 is not set/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_xiaomi_ax3600=y/g' .config
               && echo "CONFIG_KMOD_ALL=y" >> .config 
               && echo "CONFIG_FEED_custom_packages=n" >> .config
                           
            - name: Print initial config we are using
              run: cat .config

            - name: Generate full config
              run:  make defconfig V=s

            - name: Pre-download
              run: make download -j$(nproc) V=s
              
            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s  

            - name: Build firmware images
              run: make -j$(($(nproc)+1)) V=s

            - name: Get the current date
              run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

            - name: Create a release
              uses: "ncipollo/release-action@v1"
              with:
                name: "Updated prebuilt images (NSS) ${{ env.NOW }}"
                commit: "qualcommax-6.x-nss-wifi"
                tag: "ipq807x-nss-${{ env.NOW }}"
                generateReleaseNotes: true
                makeLatest: true
                artifacts: bin/targets/qualcommax/ipq807x/*
                token: "${{ secrets.GITHUB_TOKEN }}"





